export const wordsArr = [
    {title: "Red",
    photo: "https://funart.pro/uploads/posts/2021-04/1618554563_39-funart_pro-p-oboi-fon-svetlo-krasnii-tsvet-40.jpg",
    mean: "color",
    transcript: "|red|",
    translate: "Красный",
    theme: "Colors",
    sample: "red dress",
    isActive: false,

    },
    {title: "Blue",
    photo: "https://miro.medium.com/max/1280/0*xCXUvGbrpndOWTw5.jpg",
    mean: "color",
    transcript: " |bluː| ",
    translate: "Синий",
    theme: "Colors",
    sample: "blue hat",
    isActive: false
    },
    {title: "Yellow",
    photo: "https://funart.pro/uploads/posts/2021-04/1618493424_5-funart_pro-p-oboi-fon-zheltii-tsvet-6.png",
    mean: "color",
    transcript: "|ˈjeləʊ| ",
    translate: "Жёлтый",
    theme: "Colors",
    sample: "yellow shirt",
    isActive: false
    },

    {title: "Black",
    photo: "https://bogatyr.club/uploads/posts/2021-11/thumbs/1636953181_5-bogatyr-club-p-glubokii-chernii-fon-5.jpg",
    mean: "color",
    transcript: "|blæk| ",
    translate: "Чёрный",
    theme: "Colors",
    sample: "black coat",
    isActive: false
    },

    {title: "White",
    photo: "",
    mean: "color",
    transcript: "|pɪŋk| ",
    translate: "Белый",
    theme: "Colors",
    sample: "pink car",
    isActive: false
    },

    {title: "Orange",
    photo: "",
    mean: "color",
    transcript: "|pɪŋk| ",
    translate: "Оранжевый",
    theme: "Colors",
    sample: "pink car",
    isActive: false
    },
    {title: "Green",
    photo: "",
    mean: "color",
    transcript: "|pɪŋk| ",
    translate: "Зелёный",
    theme: "Colors",
    sample: "pink car",
    isActive: false
    },
    {title: "Gray",
    photo: "",
    mean: "color",
    transcript: "|pɪŋk| ",
    translate: "Серый",
    theme: "Colors",
    sample: "pink car",
    isActive: false
    },
    {title: "Golden",
    photo: "",
    mean: "color",
    transcript: "|pɪŋk| ",
    translate: "Золотой",
    theme: "Colors",
    sample: "pink car",
    isActive: false
    },

    {title: "Silver",
    photo: "",
    mean: "color",
    transcript: "|pɪŋk| ",
    translate: "Серебристый",
    theme: "Colors",
    sample: "pink car",
    isActive: false
    },
    {title: "Ivory",
    photo: "",
    mean: "color",
    transcript: "|pɪŋk| ",
    translate: "Слоновая кость",
    theme: "Colors",
    sample: "pink car",
    isActive: false
    },
    {title: "Brown",
    photo: "",
    mean: "color",
    transcript: "",
    translate: "Коричневый",
    theme: "Colors",
    sample: "",
    isActive: false
    },
    {title: "Turquoise",
    photo: "",
    mean: "color",
    transcript: "",
    translate: "Бирюзовый",
    theme: "Colors",
    sample: "",
    isActive: false
    },
    
    
    
    ]

 